### PR TITLE
Either generalization up to MonadError

### PR DESCRIPTION
**Pull request by phaazon**
I’ve been using that function a lot in a lot of projects of mine. For people like me who love typeclasses constraint instead of nasty transformers stack, that function is pretty great.

Not sure about the name though.

### CODE REVIEW

**Comment by phaazon** [comment]
Hey hey @ekmett!

**Comment by ekmett** [comment]
Not sure about the name but :+1: on the idea.

**Comment by bitemyapp** [comment]
@phaazon perhaps errorEither, eitherToError or something a little more indicative of the use of MonadError?

**Comment by phaazon** [comment]
In the first place I named it `eitherToError`, yeah. If you think it’s a better name, I’ll switch to `eitherToError`, even I find that one a bit ugly.

**Comment by phaazon** [comment]
Is there any way to know whether my PR is merged?

**Comment by ekmett** [comment]
I haven't had a chance to actually touch this package this week. I put this off looking for a better name, then things came up.

**Comment by phaazon** [comment]
Yeah, I understand. I think `eitherToError` is straight-forward enough, but it’s up to you.

**Pull request merged**
