### PR TITLE
Delete instance Alternative Validation. It breaks the right identity …

### LINKED ISSUE #50: Validation Alternative breaks right identity law
`Failure "x" <|> empty` should be `Failure "x"` but it is `empty` (`Failure ""`)

The Alt and `<|>` bias in the failure case, hence are not collecting in the semigroup. But the `empty` is for a non-biased collecting failure case. They do not agree. We should pick a side.

The options as I see them are a biased, non-collecting `Alt`, that does not have an `Alternative`, or a collecting Alt to match the current monoidish Alternative.

My vote is to keep the biased, non-collecting `Alt`, and delete the `Alternative`. The collecting instance does not satisfy the right distributive law, which we might care about depending on what we think `Alternative` means.

### PR DESCRIPTION
**Pull request by gwils**
…law.

Closes #50

### CODE REVIEW

**Comment by bitemyapp** [comment]
Not saying you have to, but is it worth adding some property checks to prevent this?

**Comment by gwils** [comment]
Yeah, I think adding them is a good idea, although I don't want to be the one to add them at the moment.

**Comment by gwils** [comment]
As mentioned in #50, we have two options.
I can see two sensible `Alt` instances for this type. I'll refer to them as "collecting" or "last". Both of these obey the `Alt` laws. Only one of these (collecting) has a matching `Alternative`.

Currently we have the last `Alt` and the collecting `Alternative`, so they don't agree! Hence we're currently breaking an `Alternative` law.
I see two options to go forward: either change the `Alt` to collecting to match the `Alternative`, or delete the `Alternative`, preferring to keep the last `Alt`.

I prefer to delete the `Alternative`, hence this PR. The reason is that the last `Alt` has a left distributivity law that the collecting `Alt` does not.

`f <*> (a <!> b) == (f <*> a) <!> (f <*> b)`

**Comment by bitemyapp** [comment]
@ekmett Seems like it's worth it to delete the instance by merging this PR, particularly given changing the instance's semantics in-place is icky. Having it be in sync with `AccValidation`'s instances to avoid confusion is worthwhile too. My stuff'll be along eventually as I get more coverage.

**Comment by ekmett** [comment]
I confess I'm leaning towards taking the other approach, which is, switching to the collecting Alternative, as literally the only purpose of Validation is to collect errors. It seems obvious to me that the current instance is a mistake.

Motivating this: `Either`/`Maybe` generally fall into the "Left Catch" rather than "Left Distributive" model of `Alternative`.

A fixed "collecting" Alternative should pass "Left Catch".

**Comment by ekmett** [comment]
We're going the other way here.

**Pull request closed without merging**
