### PR TITLE
add `catRight` and `catLefts` functions

### PR DESCRIPTION
**Pull request by s9gf4ult**
```haskell
-- | Extract all right elements from list of Either values
--
-- >>> catRights [Right 1, Left 2, Right 3]
-- [1,3]
catRights :: [Either a b] -> [b]
catRights []          = []
catRights (Right b:x) = b:catRights x
catRights (_:x)       = catRights x

-- | Extract all left elements from list of Either values
--
-- >>> catLefts [Right 1, Left 2, Right 3]
-- [2]
catLefts :: [Either a b] -> [a]
catLefts []         = []
catLefts (Left a:x) = a:catLefts x
catLefts (_:x)      = catLefts x
```

### CODE REVIEW

**Comment by phaazon** [comment]
See [lefts](https://hackage.haskell.org/package/base-4.2.0.1/docs/Data-Either.html#v%3Alefts) and [rights](https://hackage.haskell.org/package/base-4.2.0.1/docs/Data-Either.html#v%3Arights).

**Comment by ekmett** [comment]
As phaazon noted, this is already supplied by base.

**Comment by s9gf4ult** [comment]
Oh, such fail, sory.

**Comment by phaazon** [comment]
However, that makes me think the `cat*` naming is really bad. `catMaybes` should be called `justs`.

**Comment by s9gf4ult** [comment]
It is logical

**Pull request closed without merging**
