### PR TITLE
Add a generic MonadEither class

### PR DESCRIPTION
**Pull request by jotrk**
This class facilitates writing generic code, independent of the actual
Transformer stack.

### CODE REVIEW

**Comment by phaazon** [comment]
That looks like a lot a patch I submitted a few days ago. See `eitherToError`.

**Comment by jotrk** [comment]
You're reusing the `MonadError` class, pretty clever.  
However, I'm not sure how I should feel about this. Would having a dedicated `MonadEither` class any advantage? Any other opinions?

**Comment by phaazon** [comment]
I don’t understand what semantics you catch with `MonadEither`. May you argue further?

**Comment by jotrk** [comment]
I wanted to be able to write functions like so:

    producesEither :: Monad m => m (Either a b)
    producesEither = ..

    producesEither' :: MonadEither m => m b
    producesEither' = hoistEither producesEither

    arbitraryFunction :: (MonadEither m, MonadReader T m, MonadState U m, ..) => m V
    arbitraryFunction = do
        producesEither' >>= ..

But I think I could do the same with `MonadError` as well. Otoh, now I'm just
wondering what EitherT is actually good for, when you can transform any Either
into a Result or an Error

**Comment by phaazon** [comment]
I use `EitherT` to implement `MonadError`, but I never use it directly actually. Or that’s very rare.

**Comment by jotrk** [comment]
I see. I've used `EitherT` with [xhb](http://hackage.haskell.org/package/xhb) because the server replies are all `Either`s. Since I'm using a more complex transformer stack for my program I wanted to use mainly constraints instead of a concrete stack and lifting. But I can transform it easily to `MonadError`.

So, how should we go about this? Shall I retract my PR? Or do you want to wait for @ekmett 's opinion?

**Comment by ekmett** [comment]
`MonadError` provides precisely what is needed by `EitherT`.

The issue that caused the creation of `EitherT` was the `Error` constraint on `ErrorT`, not the methods in the class.

**Comment by jotrk** [comment]
I understand. Thank you everyone for the clarification and explanation! I'm closing this now.

**Pull request closed without merging**
